"""Schema inference engine.

Three execution modes, all returning the same `SchemaInferenceResult` contract:

1. **Bedrock mode**: Claude via Amazon Bedrock. Needs `bedrock:InvokeModel` on the model id.
2. **Anthropic mode**: Claude via api.anthropic.com directly. Needs `ANTHROPIC_API_KEY`.
3. **Local mock mode**: deterministic heuristic classifier — same output shape, no network.

`auto` (default) tries bedrock → anthropic → local in order, falling back on any failure.
"""

from __future__ import annotations

import json
import logging
import os
import re
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .prompts import (
    CANONICAL_FIELDS,
    PII_TIERS,
    PROMPT_VERSION,
    SYSTEM_PROMPT,
    build_user_prompt,
)

log = logging.getLogger(__name__)

# Cross-region inference profile (us.* prefix is AWS-managed and required for
# Claude 4.x family on Bedrock — direct on-demand model IDs are no longer accepted
# for these models). The profile auto-routes to the nearest region with capacity.
DEFAULT_BEDROCK_MODEL = "us.anthropic.claude-sonnet-4-6"
DEFAULT_ANTHROPIC_MODEL = "claude-sonnet-4-6"
DEFAULT_REGION = "us-east-1"


@dataclass
class ColumnInference:
    source_column: str
    canonical_field: str
    confidence: float
    pii_tier: str
    cleansing_rules: list[str] = field(default_factory=list)
    reasoning: str = ""


@dataclass
class SchemaInferenceResult:
    filename: str
    detected_format: str
    columns: list[ColumnInference]
    overall_quality_risk: str
    overall_quality_notes: str
    suggested_partition_column: str | None
    prompt_version: str
    model_id: str
    inferred_at: str
    mode: str  # "bedrock" or "local_mock"

    def to_dict(self) -> dict[str, Any]:
        d = asdict(self)
        return d

    def to_data_contract_yaml(self) -> str:
        """Render the inference as a draft data contract YAML for human review."""
        lines = [
            f"# DRAFT data contract — review before promoting to production",
            f"# Generated by schema-inference {self.prompt_version} ({self.mode})",
            f"# Inferred at: {self.inferred_at}",
            f"",
            f"partner_id: REPLACE_ME",
            f"contract_version: 1",
            f"source_format: {self.detected_format}",
            f"partition_column: {self.suggested_partition_column or 'effective_start_date'}",
            f"overall_quality_risk: {self.overall_quality_risk}",
            f"reviewed_by: REPLACE_ME",
            f"reviewed_at: REPLACE_ME",
            f"",
            f"columns:",
        ]
        for c in self.columns:
            lines.append(f"  - source_column: \"{c.source_column}\"")
            lines.append(f"    canonical_field: {c.canonical_field}")
            lines.append(f"    confidence: {c.confidence:.2f}")
            lines.append(f"    pii_tier: {c.pii_tier}")
            if c.cleansing_rules:
                lines.append(f"    cleansing_rules:")
                for rule in c.cleansing_rules:
                    lines.append(f"      - {rule}")
            lines.append(f"    reasoning: \"{c.reasoning}\"")
        return "\n".join(lines)


def infer_schema(
    filename: str,
    sample_rows: list[dict[str, Any]],
    *,
    mode: str | None = None,
    model_id: str | None = None,
    region: str | None = None,
) -> SchemaInferenceResult:
    """Infer a draft schema for an unknown partner file.

    Args:
        filename: name of the file (used for context in the prompt)
        sample_rows: a list of dicts representing the first ~50 rows of the file
        mode: "bedrock" or "local" — overrides env-driven default
        model_id: Bedrock model identifier; defaults to Claude Sonnet 4.6
        region: AWS region for Bedrock; defaults to us-east-1

    Returns:
        SchemaInferenceResult with column mappings and quality assessment.
    """
    if not sample_rows:
        raise ValueError("sample_rows cannot be empty")

    chosen_mode = (mode or os.environ.get("LORE_SCHEMA_INFERENCE_MODE", "auto")).lower()
    chosen_model = model_id or os.environ.get("LORE_BEDROCK_MODEL", DEFAULT_BEDROCK_MODEL)
    chosen_region = region or os.environ.get("AWS_REGION", DEFAULT_REGION)

    if chosen_mode == "local":
        return _infer_local(filename, sample_rows, chosen_model)

    if chosen_mode == "bedrock":
        return _infer_bedrock(filename, sample_rows, chosen_model, chosen_region)

    if chosen_mode == "anthropic":
        anthro_model = os.environ.get("LORE_ANTHROPIC_MODEL", DEFAULT_ANTHROPIC_MODEL)
        return _infer_anthropic(filename, sample_rows, anthro_model)

    # auto mode: try bedrock → anthropic → local
    try:
        return _infer_bedrock(filename, sample_rows, chosen_model, chosen_region)
    except Exception as exc:
        log.warning("Bedrock inference failed (%s), trying Anthropic API", exc)
    if os.environ.get("ANTHROPIC_API_KEY"):
        try:
            anthro_model = os.environ.get("LORE_ANTHROPIC_MODEL", DEFAULT_ANTHROPIC_MODEL)
            return _infer_anthropic(filename, sample_rows, anthro_model)
        except Exception as exc:
            log.warning("Anthropic API inference failed (%s), falling back to local mock", exc)
    return _infer_local(filename, sample_rows, chosen_model)


def _infer_bedrock(
    filename: str,
    sample_rows: list[dict[str, Any]],
    model_id: str,
    region: str,
) -> SchemaInferenceResult:
    """Call Bedrock Claude with the structured prompt. Returns the parsed result."""
    try:
        import boto3  # imported lazily so local mode works without AWS deps
    except ImportError as e:
        raise RuntimeError("boto3 is required for Bedrock mode") from e

    client = boto3.client("bedrock-runtime", region_name=region)
    user_prompt = build_user_prompt(filename, sample_rows[:50], CANONICAL_FIELDS, PII_TIERS)

    body = {
        "anthropic_version": "bedrock-2023-05-31",
        "max_tokens": 4000,
        "system": SYSTEM_PROMPT,
        "messages": [{"role": "user", "content": user_prompt}],
        "temperature": 0.0,  # deterministic for the structured-output use case
    }

    resp = client.invoke_model(
        modelId=model_id,
        body=json.dumps(body),
        contentType="application/json",
        accept="application/json",
    )
    payload = json.loads(resp["body"].read())
    text = payload["content"][0]["text"]
    parsed = _extract_json(text)
    return _result_from_dict(filename, parsed, model_id, mode="bedrock")


def _infer_anthropic(
    filename: str,
    sample_rows: list[dict[str, Any]],
    model_id: str,
) -> SchemaInferenceResult:
    """Call Claude via the Anthropic API directly. Same prompt + parsing as Bedrock path."""
    import urllib.request
    import urllib.error

    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        raise RuntimeError("ANTHROPIC_API_KEY is not set")

    user_prompt = build_user_prompt(filename, sample_rows[:50], CANONICAL_FIELDS, PII_TIERS)
    body = {
        "model": model_id,
        "max_tokens": 4000,
        "system": SYSTEM_PROMPT,
        "messages": [{"role": "user", "content": user_prompt}],
        "temperature": 0.0,
    }
    req = urllib.request.Request(
        "https://api.anthropic.com/v1/messages",
        data=json.dumps(body).encode("utf-8"),
        headers={
            "x-api-key": api_key,
            "anthropic-version": "2023-06-01",
            "content-type": "application/json",
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=60) as resp:
            payload = json.loads(resp.read())
    except urllib.error.HTTPError as e:
        detail = e.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"Anthropic API HTTP {e.code}: {detail[:300]}") from e

    text = payload["content"][0]["text"]
    parsed = _extract_json(text)
    return _result_from_dict(filename, parsed, model_id, mode="anthropic")


def _result_from_dict(
    filename: str, parsed: dict, model_id: str, *, mode: str
) -> SchemaInferenceResult:
    cols = [
        ColumnInference(
            source_column=c["source_column"],
            canonical_field=c["canonical_field"],
            confidence=float(c["confidence"]),
            pii_tier=c["pii_tier"],
            cleansing_rules=list(c.get("cleansing_rules", [])),
            reasoning=c.get("reasoning", ""),
        )
        for c in parsed["columns"]
    ]
    return SchemaInferenceResult(
        filename=filename,
        detected_format=parsed.get("detected_format", "unknown"),
        columns=cols,
        overall_quality_risk=parsed.get("overall_quality_risk", "MEDIUM"),
        overall_quality_notes=parsed.get("overall_quality_notes", ""),
        suggested_partition_column=parsed.get("suggested_partition_column"),
        prompt_version=PROMPT_VERSION,
        model_id=model_id,
        inferred_at=datetime.now(timezone.utc).isoformat(),
        mode=mode,
    )


def _extract_json(text: str) -> dict:
    """Robustly extract a JSON object from an LLM response.

    Claude is prompted for JSON-only output, but in practice we still see occasional
    leading/trailing whitespace or markdown fences. We strip those and try to parse.
    """
    text = text.strip()
    # Strip ```json ... ``` if present
    fenced = re.match(r"```(?:json)?\s*(.*?)\s*```", text, re.DOTALL)
    if fenced:
        text = fenced.group(1)
    # Find first { and last } as a last resort
    start = text.find("{")
    end = text.rfind("}")
    if start >= 0 and end > start:
        text = text[start : end + 1]
    return json.loads(text)


# ---------------------------------------------------------------------------
# Local mock — deterministic heuristic classifier
# ---------------------------------------------------------------------------

# Pattern → (canonical_field, pii_tier, cleansing_rules, reasoning)
_HEURISTICS: list[tuple[re.Pattern, str, str, list[str], str]] = [
    (re.compile(r"^(ssn|social|tax_id|tin)$", re.I), "ssn", "TIER_1_DIRECT",
     ["validate_ssn_format", "tokenize_via_skyflow", "store_last_4_only"],
     "Column header indicates SSN."),
    (re.compile(r"^(dob|date_of_birth|birth_date|birthday)$", re.I), "dob", "TIER_1_DIRECT",
     ["coerce_iso8601_date"], "Column header indicates date of birth."),
    (re.compile(r"^(first_?name|fname|given_?name)$", re.I), "first_name", "TIER_1_DIRECT",
     ["strip_whitespace", "title_case_with_diacritics"], "Header indicates first name."),
    (re.compile(r"^(last_?name|lname|surname|family_?name)$", re.I), "last_name", "TIER_1_DIRECT",
     ["strip_whitespace", "title_case_with_diacritics"], "Header indicates last name."),
    (re.compile(r"^(middle_?name|mname|middle_initial|mi)$", re.I), "middle_name", "TIER_1_DIRECT",
     ["strip_whitespace"], "Header indicates middle name."),
    (re.compile(r"^(email|email_address|e_mail)$", re.I), "email", "TIER_1_DIRECT",
     ["lowercase", "rfc5322_validate", "tokenize_via_skyflow"], "Header indicates email."),
    (re.compile(r"^(phone|phone_number|tel|mobile)$", re.I), "phone", "TIER_1_DIRECT",
     ["e164_normalize", "tokenize_via_skyflow"], "Header indicates phone number."),
    (re.compile(r"^(addr|address|street|address_?line_?1|address1)$", re.I), "address_line_1",
     "TIER_1_DIRECT", ["usps_validate", "tokenize_via_skyflow"], "Header indicates street address."),
    (re.compile(r"^(addr2|address_?line_?2|address2|apt|unit|suite)$", re.I), "address_line_2",
     "TIER_1_DIRECT", ["usps_validate"], "Header indicates address line 2."),
    (re.compile(r"^city$", re.I), "city", "TIER_2_QUASI",
     ["title_case", "usps_validate"], "Header indicates city."),
    (re.compile(r"^(state|st|province)$", re.I), "state", "TIER_2_QUASI",
     ["uppercase", "validate_us_state_abbrev"], "Header indicates state."),
    (re.compile(r"^(zip|zipcode|postal_?code)$", re.I), "zip", "TIER_2_QUASI",
     ["pad_to_5_digits"], "Header indicates ZIP."),
    (re.compile(r"^(zip4|plus4|zip_plus4)$", re.I), "zip4", "TIER_2_QUASI",
     [], "Header indicates ZIP+4."),
    (re.compile(r"^(member_?id|partner_?member_?id|memberid|external_?id|emp(loyee)?_?id|subscriber_?id)$", re.I),
     "partner_member_id", "TIER_4_NONE",
     ["strip_whitespace"], "Header indicates partner-side member identifier."),
    (re.compile(r"^(gender|sex)$", re.I), "gender", "TIER_2_QUASI",
     ["normalize_to_M_F_X_U"], "Header indicates gender."),
    # Match anywhere in the header (substring) — handles "EligStartDate", "CoverageStartDate", "Effective_Start", etc.
    (re.compile(r"(elig|effective|coverage)[_ ]?start|^start[_ ]?date$", re.I),
     "effective_start_date", "TIER_3_SENSITIVE",
     ["coerce_iso8601_date"], "Header indicates eligibility/coverage start."),
    (re.compile(r"(elig|effective|coverage|term)[_ ]?(end|term)|^end[_ ]?date$|^termination$", re.I),
     "effective_end_date", "TIER_3_SENSITIVE",
     ["coerce_iso8601_date"], "Header indicates eligibility/coverage end."),
    (re.compile(r"^(plan|plan_?code|product|product_?code)$", re.I), "plan_code", "TIER_3_SENSITIVE",
     ["uppercase"], "Header indicates plan/product code."),
    (re.compile(r"^(employer|employer_?name|company|group)$", re.I), "employer_name", "TIER_2_QUASI",
     ["strip_whitespace"], "Header indicates employer."),
    (re.compile(r"^(suffix|name_suffix)$", re.I), "suffix", "TIER_1_DIRECT",
     [], "Header indicates name suffix."),
]

# Value-shape patterns (used when header is ambiguous)
_SSN_RE = re.compile(r"^\d{3}-?\d{2}-?\d{4}$")
_DOB_RE = re.compile(r"^\d{4}[-/]\d{1,2}[-/]\d{1,2}$|^\d{1,2}[-/]\d{1,2}[-/]\d{2,4}$")
_EMAIL_RE = re.compile(r"^[^@\s]+@[^@\s]+\.[^@\s]+$")
_ZIP_RE = re.compile(r"^\d{5}(-\d{4})?$")
_PHONE_RE = re.compile(r"^[\+\-\.\(\) \d]{7,20}$")


def _infer_local(
    filename: str, sample_rows: list[dict[str, Any]], model_id: str
) -> SchemaInferenceResult:
    """Heuristic classifier. Mimics Bedrock output schema."""
    headers = list(sample_rows[0].keys())
    columns: list[ColumnInference] = []

    for header in headers:
        match = next((h for h in _HEURISTICS if h[0].search(header)), None)
        if match:
            _, canon, tier, rules, reason = match
            columns.append(
                ColumnInference(
                    source_column=header,
                    canonical_field=canon,
                    confidence=0.92,
                    pii_tier=tier,
                    cleansing_rules=list(rules),
                    reasoning=reason,
                )
            )
            continue

        # Header didn't match. Sniff values.
        values = [str(r.get(header, "")) for r in sample_rows[:20] if r.get(header)]
        canon, tier, rules, reason, conf = _sniff_values(values)
        columns.append(
            ColumnInference(
                source_column=header,
                canonical_field=canon,
                confidence=conf,
                pii_tier=tier,
                cleansing_rules=rules,
                reasoning=reason,
            )
        )

    overall_risk = _overall_risk(columns)
    detected_format = _detect_format(filename)
    suggested_partition = _suggest_partition(columns)

    return SchemaInferenceResult(
        filename=filename,
        detected_format=detected_format,
        columns=columns,
        overall_quality_risk=overall_risk,
        overall_quality_notes=(
            "Local heuristic inference. Review every column with confidence < 0.85 "
            "and re-run with Bedrock when AWS access is available for production promotion."
        ),
        suggested_partition_column=suggested_partition,
        prompt_version=PROMPT_VERSION,
        model_id=model_id,
        inferred_at=datetime.now(timezone.utc).isoformat(),
        mode="local_mock",
    )


def _sniff_values(values: list[str]) -> tuple[str, str, list[str], str, float]:
    if not values:
        return ("ignore", "TIER_4_NONE", [], "Empty column.", 0.5)
    sample = values[: min(len(values), 20)]
    if all(_SSN_RE.match(v) for v in sample):
        return ("ssn", "TIER_1_DIRECT",
                ["validate_ssn_format", "tokenize_via_skyflow"],
                "Values match SSN pattern.", 0.85)
    if all(_EMAIL_RE.match(v) for v in sample):
        return ("email", "TIER_1_DIRECT",
                ["lowercase", "tokenize_via_skyflow"], "Values look like emails.", 0.85)
    if all(_DOB_RE.match(v) for v in sample):
        return ("dob", "TIER_1_DIRECT", ["coerce_iso8601_date"],
                "Values look like dates.", 0.7)
    if all(_ZIP_RE.match(v) for v in sample):
        return ("zip", "TIER_2_QUASI", ["pad_to_5_digits"],
                "Values look like US ZIPs.", 0.8)
    if all(_PHONE_RE.match(v) for v in sample):
        return ("phone", "TIER_1_DIRECT", ["e164_normalize", "tokenize_via_skyflow"],
                "Values look like phone numbers.", 0.65)
    return ("ignore", "TIER_4_NONE", [],
            "No strong signal from header or values; flagging for human review.", 0.4)


def _overall_risk(columns: list[ColumnInference]) -> str:
    pii_count = sum(1 for c in columns if c.pii_tier == "TIER_1_DIRECT")
    low_conf = sum(1 for c in columns if c.confidence < 0.7)
    if low_conf > len(columns) / 3:
        return "HIGH"
    if pii_count >= 4 or low_conf > 2:
        return "MEDIUM"
    return "LOW"


def _detect_format(filename: str) -> str:
    suffix = Path(filename).suffix.lower()
    return {
        ".csv": "csv",
        ".tsv": "tsv",
        ".json": "json",
        ".jsonl": "jsonl",
        ".ndjson": "jsonl",
        ".edi": "x12_834",
        ".834": "x12_834",
        ".txt": "fixed_width",
    }.get(suffix, "other")


def _suggest_partition(columns: list[ColumnInference]) -> str | None:
    for c in columns:
        if c.canonical_field == "effective_start_date":
            return c.source_column
    for c in columns:
        if c.canonical_field == "dob":
            return c.source_column
    return None
